nelmio_api_doc:
  documentation:
    info:
      title: BileMo API
      description: This is an API dedicated to a business of smartphone products
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
